### ISSUE TITLE
pyperclip.paste() does not work when typed in IDLE

### ISSUE THREAD

**Issue by brandodo** [asweigart/pyperclip#102]
Hi, I am fairly new to Python and have started learning this language since a few days ago. I am having some trouble with getting the paste method to work for the pyperclip module and was hoping someone could shed some light on this.

The issue I am having is that when I try to run the following code in IDLE:
```
import pyperclip

pyperclip.copy('Hi')
pyperclip.paste()
```

The result comes out as this in the shell:
```
============ RESTART: /Users/b.ong/Desktop/Desktop/Python/test.py ============
>>> 
```

However, when I typed "pyperclip.paste()" directly into the shell, it pastes the text that was copied.

Not sure what to do here and would appreciate some help.

Thanks in advance!

**Comment by anonymoose2** [comment]
Try `print(pyperclip.paste())`.

When you run it as a script, Python doesn't recognize that you want it to print the result. It just calls the function. Since you didn't tell it to do anything with the result, it throws it away.

**Comment by brandodo** [comment]
That works! 

Thanks!

**Comment by Yvad60** [comment]
you saved me

**Comment by franck070** [comment]
Thank you anonymoose2 ****
