### ISSUE TITLE
Load both the X clipboard *and* the GTK one.

### ISSUE THREAD

**Issue by vext01** [asweigart/pyperclip#11]
Hi,

I see that pyperclip will load the first clipboard it can using whichever tool it can. The code looks like this:

```
    # Set one of the copy & paste functions.
    if xclipExists:
        _functions = 'xclip command' # for debugging
        paste = _pasteXclip
        copy = _copyXclip
    elif gtkInstalled:
        _functions = 'gtk module' # for debugging
        paste = _pasteGtk
        copy = _copyGtk
    elif ...
```

This means, on a posix system, we load either the X clipboard (a.k.a. the PRIMARY clipboard ), _or_ the GTK one (a.k.a. the CLIPBOARD clipboard).

I would like to load _both_ of these clipboards.

I suppose we would need `_copyGtkAndXclip` and a `pasteGtkAndXclip` functions.

**Comment by vext01** [comment]
I started playing around, but realised that we would need to think which clipboards each method is responsible for loading.

FWIW: https://github.com/vext01/pyperclip/commits/primary_and_selection

Needs more thought.

**Comment by pwnage101** [comment]
I'm asserting that this issue is now invalid since pyperclip now only loads the CLIPBOARD selection regardless of the chosen backend.

Somebody please confirm and close this issue.

**Comment by pwnage101** [comment]
Active PR #66 addresses being able to access both the PRIMARY and the CLIPBOARD selection with `pyperclip.paste(primary=True)` and `pyperclip.paste()` respectively.  If that's what this issue is referring to, then merging #66 should also lead to closing this issue.

**Comment by asweigart** [comment]
#66 has been merged.
