### ISSUE TITLE
Support wayland?

### ISSUE THREAD

**Issue by Losses** [asweigart/pyperclip#141]
Will this lib support Wayland by adding `wl-clipboard`?

https://github.com/bugaevc/wl-clipboard

**Comment by ankostis** [comment]
Or this trick?
https://www.geekyhub.in/post/use-xclip-in-gnome-wayland/

**Comment by Losses** [comment]
@ankostis I'm so happy that someone noticed this issue after 7 months 😂

**Comment by ankostis** [comment]
Actually i crafted a PR #141 to solve it (but has some problems that needs to be fixed).

**Comment by JohnnyNom** [comment]
@Losses thank you for turning me on to wl-clipboard!
@ankostis  thank you for the check for wayland!

I used subprocess to call wl-copy: `subprocess.run(["wl-copy","Copy_this"])`
