### ISSUE TITLE
Cannot use it with Docker

### ISSUE THREAD

**Issue by joaogabrielzo** [asweigart/pyperclip#161]
I tried to Dockerize my application and everytime I get "Pyperclip could not find a copy/paste mechanism for your system."

I have tried installing xclip, xsel and the Python packages that might be needed, but I still be getting this error.

I tried using ubuntu:18.04 base image.

**Comment by loopinf** [comment]
Same behavior with me.

**Comment by ra100** [comment]
Seems we have the same/similar issue, we're using pyperclip with RobotFramework, using just `pyperclip.copy(text)` and `pyperclip.paste()` and when we run it locally, it works fine. But inside the docker we always get empty string from the clipboard.

**Comment by lovelytxm** [comment]
This also happens with me. i try to run  robotframework on Docker. but this pyperclip is not work.

**Comment by lovelytxm** [comment]
Hi,
I fixed the issue now.  need to simulate a display in docker. It works well. 
step:
1. apt-get install  xvfb
2. apt-get install xclip
3. set a display
   a. /# Xvfb :99 -screen 0 1280x720x16 &
   b. /# export DISPLAY=:99

**Comment by rightx2** [comment]
@lovelytxm I've tried but didn't work
```
RUN apt-get install -y xclip xvfb
RUN Xvfb :99 -screen 0 1280x720x16 &
RUN export DISPLAY=:99
```

Did i miss something?

**Comment by merwok** [comment]
yes, xvfb creates a fake X context so that X programs can work.  it’s not the same as giving access to the host X server.

**Comment by merwok** [comment]
this isn’t the place to explain how X clients connect to the X server, but here are examples of docker containers and run commands for graphical apps: https://blog.jessfraz.com/post/docker-containers-on-the-desktop/#guis

**Comment by caarmen** [comment]
> I've tried but using pyperclip failed...
> 
> Below is part of my Dockerfile
> 
> ```
> ...
> RUN apt-get install -y xclip xvfb
> RUN Xvfb :99 -screen 0 1280x720x16 &
> RUN export DISPLAY=:99
> ```
> 
> Did I miss something?

I tried this and it worked for my use case:
```
RUN apt-get install -y xclip xvfb
ENV DISPLAY=:99
RUN nohup bash -c "Xvfb :99 -screen 0 1280x720x16 &"
```
