### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by sobujbd** [asweigart/pyperclip#163]
I'm trying to copy [Bangla Text](https://en.wikipedia.org/wiki/Bengali_alphabet). But copied text stored as **???**

**Comment by shoccho** [comment]
The issue might be with something else . because I've used it in my project with Bengali language ( UTF_8 ). and I just tested it seemed to work fine. 

![screenshot](https://i.ibb.co/JqvrK8r/Screenshot-from-2020-08-12-21-54-46.png)

python 3.8.2

**Comment by asweigart** [comment]
This has more to do with Windows and Command Prompt, which cannot display all UTF-8 characters such as Bengali, rather than pyperclip. I've checked and Pyperclip is able to copy & paste Bengali characters, though they aren't viewable in Command Prompt.
