### ISSUE TITLE
use PyObjC if available

### ISSUE THREAD

**Issue by arkarkark** [asweigart/pyperclip#18]
rather than forking a new process for every copy/paste it'd be nice to use the os libraries (if available)

http://blog.carlsensei.com/post/88897796

Those are available if you have this
https://pythonhosted.org/pyobjc/install.html

``` python
import Foundation, AppKit

def pbcopy(s):
    "Copy string argument to clipboard"
    newStr = Foundation.NSString.stringWithString_(s).nsstring()
    newData = newStr.dataUsingEncoding_(Foundation.NSUTF8StringEncoding)
    board = AppKit.NSPasteboard.generalPasteboard()
    board.declareTypes_owner_([AppKit.NSStringPboardType], None)
    board.setData_forType_(newData, AppKit.NSStringPboardType)

def pbpaste():
    "Returns contents of clipboard"
    board = AppKit.NSPasteboard.generalPasteboard()
    content = board.stringForType_(AppKit.NSStringPboardType)
    return content
```

**Comment by asweigart** [comment]
Thanks! I'll add this since it's probably but faster than running pbcopy/pbpaste.

**Comment by jaraco** [comment]
In the meantime, consider using [richxerox](https://pypi.io/project/richxerox) or [jaraco.clipboard](https://pypi.io/project/jaraco.clipboard) for an implementation that relies on pyobjc.
