### ISSUE TITLE
Importing into my library results in module not found

### ISSUE THREAD

**Issue by mwd1993** [asweigart/pyperclip#181]
I'm importing into my library, but the end user must have pyperclip installed I believe? Is there a way to ship my pypi project with a working pyperclip by simply just importing it? Did this functionality recently break?

Thanks.

**Comment by asweigart** [comment]
Yes, you need to add 'pyperclip' as an entry for the install_requires list in your module's setup.py. This will install pyperclip when a user installs your module.
