### ISSUE TITLE
Paste only pastes in the terminal and not anywhere else

### ISSUE THREAD

**Issue by ShobanChiddarth** [asweigart/pyperclip#188]
Im using pyautogui with pyperclip (because it had multiple bugs and I reported them too)
Here is my code
```
import pyautogui
import pyperclip
import time
pyperclip.copy("• ")
for x in range(1):
    time.sleep(3)
    pyautogui.press("home")
    pyperclip.paste()
```
But I only see the "• " in the terminal where it is running so I don't get it in the text editor where I use pyautogui

**Comment by inktrap** [comment]
This is not an issue with pyperclip. Paste just prints the content of the clipboard because there is no variable to hold it. Maybe try this:

```
import pyautogui
import pyperclip
import time
pyperclip.copy("• ")
for x in range(1):
    time.sleep(3)
    pyautogui.press("home")
    clipboard_content = pyperclip.paste()
    pyautogui.typewrite(clipboard_content)
    # or: pyautogui.typewrite(pyperclip.paste())
```

Check out pyautogui docs about this.

> Key presses go to wherever the keyboard cursor is at function-calling time.

https://pyautogui.readthedocs.io/en/latest/quickstart.html

**Comment by ShobanChiddarth** [comment]
Ok thanks.
