### ISSUE TITLE
ArgumentError: argument 1: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by choies1** [asweigart/pyperclip#21]
I install pyperclip-1.5.11 for Python 3.4 on Win7.

When I run following code:

    import pyperclip
    pyperclip.paste()

I meet following error:

```
C:\pyzo2015a\lib\site-packages\pyperclip\__init__.py in _pasteWindows()
     32     CF_UNICODETEXT = 13
     33     d = ctypes.windll
---> 34     d.user32.OpenClipboard(0 if PY2 else None)
     35     handle = d.user32.GetClipboardData(CF_UNICODETEXT)
     36     data = ctypes.c_wchar_p(handle).value

ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

Please let me know what I should do to solve the problem.

**Comment by asweigart** [comment]
Could you provide the full text of the error message? I can only see where the error happened but not what the error message was.

**Comment by choies1** [comment]
The message is all error message what I saw.

**Comment by vikingspy** [comment]
I was getting the same error, on Anaconda 2.3.0 (64-bit), Python 3.4.3, pyperclip-1.5.11.  Tried changing the OpenClipboard to pass only "0" as was suggested in other issue threads, but no dice.  Then I started getting "AttributeError: 'module' object has no attribute 'copy'"

Going off of the following stackoverflow answers, I decided to delete the files in my pyperclip/_pycache_ folder, and restarted the Python kernel.  So far this (and maybe the OpenClipboard fix?) seems to have fixed everything.

http://stackoverflow.com/a/11873344
http://stackoverflow.com/questions/11568223/python-yet-another-attributeerror-module-object-has-no-attribute

**Comment by bshiwani** [comment]
I got a similar error while running the code:
``
def simxStart(connectionAddress, connectionPort, waitUntilConnected, doNotReconnectOnceDisconnected, timeOutInMs, commThreadCycleInMs):
”’
Please have a look at the function description/documentation in the V-REP user manual
”’

return c_Start(connectionAddress, connectionPort, waitUntilConnected, doNotReconnectOnceDisconnected, timeOutInMs, commThreadCycleInMs)
``
Error is:
clientID=vrep.simxStart(‘127.0.0.1’,19994,True,True,5000,5)
File “C:\Users\Capeta\Downloads\BaxterHello_V-REP-master\BaxterHello_V-REP-master\v-rep_python\vrep.py”, line 994, in simxStart
return c_Start(connectionAddress, connectionPort, waitUntilConnected, doNotReconnectOnceDisconnected, timeOutInMs, commThreadCycleInMs)
ctypes.ArgumentError: argument 1: : wrong type

Can you suggest how to solve it in this case?

Thanks
