### ISSUE TITLE
Error on Windows: OSError: exception: access violation writing 0x0000000000000000

### ISSUE THREAD

**Issue by bit0001** [asweigart/pyperclip#25]
I would like to use pyperclip to copy to clipboard and paste from it, but it seems that it is not working.

When I try to use `pyperclip.copy("some string")`, I get the following errors:

Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\site-packages\pyperclip\__init__.py", line 68, in winSetClipboard
    ctypes.cdll.msvcrt.strcpy(ctypes.c_char_p(pchData), bytes(text))
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    pyperclip.copy("hello")
  File "C:\Program Files\Python 3.5\lib\site-packages\pyperclip\__init__.py", line 71, in winSetClipboard
    ctypes.cdll.msvcrt.strcpy(ctypes.c_char_p(pchData), bytes(text, 'ascii'))
OSError: exception: access violation writing 0x0000000000000000

On the other hand, when I use `pyperclip.paste()` even if I had copied something previously, I get nothing printed, and even sometimes python crashes.

I am using windows 10 and python 3.5. I have also tried with python 3.4.3.

I have asked a question on [StackOverflow][http://stackoverflow.com/questions/32763044/pyperclip-module-not-working], and someone suggested to use pyperclip.copy(b"somestring"), and in this case I just get the second error. After informing this result, he suggested to report this as an issue, so this is it.

Thanks in advance.

**Comment by contrixed** [comment]
You are using quite an older version of this. Please update your module from pypi, please share your results after updating.

**Comment by bit0001** [comment]
FYI I am using pyperclip-1.5.13, and I am getting the errors mentioned.

**Comment by contrixed** [comment]
Alright i wasn't sure on that. Are you copying a normal string? If so then my assumption is the clipboard API might have changed, i just tested the newest version under Windows 7 here is the result.
```
import pyperclip
pyperclip.copy('aaa')
pyperclip.paste()
b'aaa'
```

However i was able to get the first error by adding an utf-8 character that is out of range. 

So the problem could be one of two things;
A) Something in your string needs to be encoded before being copied.
B) Microsoft broke the clipboard API from Windows 7 - 8 / 8.1 and now pyperclip is broken on Windows 10.

**Comment by bit0001** [comment]
Well, I am using Windows 10, and I guess that could be the problem, so what can I do in this case? I would like to use the module 'cause it seems simple and powerful.

**Comment by contrixed** [comment]
Can you copy aaa without issue or any string contain non unicode characters? If not somethings broken in pyperclip and somebody that actually uses Windows as their OS will need to take a closer look at this problem.

**Comment by bit0001** [comment]
Well, it seems the problem is Python 3.5 because I have executed:

`import pyperclip`
`pyperclip.copy("aaa")`
`pyperclip.paste()`
and it worked properly

**Comment by contrixed** [comment]
What was the original line of text that you attempted to copy/paste? Perhaps this is only a bug within pyperclip.

**Comment by bit0001** [comment]
Well I tried the run the previous lines in Python 3.5, but I have gotten those errors I have posted.

**Comment by rkhwaja** [comment]
I also see this error on windows 10 with python 3.5.
It does not occur on windows 7 with python 3.4.3 or python 3.5.
It did not occur on windows 8 with python 3.4.
It does not occur on windows 10 with python 3.4.3.

**Comment by contrixed** [comment]
That's pretty odd, so Windows 10 must be doing something that python 3.5 is not expecting. My best guess is someone is going to have to check for Windows 10 and figure out the main cause of this issue, i question if it can be this line in pyperclip that acts up with Windows 10
```python
    if not isinstance(text, text_type):
        text = text.decode('mbcs')
```

**Comment by rkhwaja** [comment]
I get the following error for python 3.5 on windows 10 64-bit:
    ctypes.cdll.msvcrt.wcscpy(ctypes.c_wchar_p(pchData), text)
OSError: exception: access violation writing 0x0000000000000000

pchData is 0
GlobalLock is returning that 0 which is an error (it's supposed to be a valid pointer to memory)
GetLastError returns 6 for that GlobalLock call, which is ERROR_INVALID_HANDLE, implying that the return value from GlobalAlloc is an invalid handle, even though the value looks OK.

Calling these functions from a Visual Studio 2013-built 64-bit exe on Windows 10 works fine. I think it's a problem with ctypes on python 3.5/Windows 10.

**Comment by contrixed** [comment]
This should be reported to the Python.

@asweigart  Perhaps the windows copy/paste method should be written in a pythonic manor as apposed to call C functions, it appears this is just problematic at this point in time.

**Comment by asweigart** [comment]
Okay, so I was able to repro this problem in 3.5 on Windows 7. I've changed the code so that 0 is passed to OpenClipboard in all cases (and it never passes None). This works for 2.6, 2.7, 3.1 through 3.5 on my Windows 7 box. Please update me if this problem still exists.

I haven't contacted python core team about this issue, so I don't know if there's a bug report open on it. I'm mostly focused on getting pyperclip to work.

**Comment by asweigart** [comment]
(Please do open this again if this error comes up again.)

**Comment by asweigart** [comment]
Nix that, I solved a different issue. I haven't been able to repro this exact error message.

**Comment by Dummie** [comment]
I'm experiencing a very similar issue with Pyperclip, but in Windows 8.1 . I'm running python 3.5 and pyperclip 1.5.15.  
  
When I try to copy a string I get:

     Traceback (most recent call last):
     File "<pyshell#8>", line 1, in <module>
     pyperclip.copy('aaa')
     File "C:\Python35\lib\site-packages\pyperclip\__init__.py", line 58, in _copyWindows
     ctypes.cdll.msvcrt.wcscpy(ctypes.c_wchar_p(pchData), text)
     OSError: exception: access violation writing 0x0000000000000000  
  
if I try to copy a number:

    Traceback (most recent call last):
    File "<pyshell#5>", line 1, in <module>
    pyperclip.copy(2)
    File "C:\Python35\lib\site-packages\pyperclip\__init__.py", line 46, in _copyWindows
    text = text.decode('mbcs')
    AttributeError: 'int' object has no attribute 'decode'  
  
I'm new to all this and I notice that some of you are running multiple versions of Python. Are you doing this on the same computer, and if so, did you have to do anything special to avoid conflicts?

**Comment by zacharykeeton** [comment]
It's 64bit python that doesn't like it.   Change to 32bit python3.5 and it works fine.  Just did it on my win 8.1.

Credit goes to this guy:
http://stackoverflow.com/questions/32676543/pyperclip-copy-causing-an-oserror

**Comment by BergWerkGIS** [comment]
Had the same issue on W10, Python 2.7 64bit.
Happened only on first call to `pyperclip.copy()`, consecutive calls succeeded.
#41 solved it, thanks.

**Comment by matham** [comment]
Just FYI having run into the exact issue since we had a version of your old code in our project. The issue was fixed by the explicit definition of `GlobalLock`. 

I.e. rather than calling `kernel32.GlobalLock (...)`, defining 

```py
GlobalLock = ctypes.windll.kernel32.GlobalLock
GlobalLock.argtypes = [HGLOBAL]
GlobalLock.restype = LPVOID
```

and calling `GlobalLock(...)` fixed it. Something in py35-x64 ctypes headers must be wrong to cause this.

**Comment by ThePlasmaRailgun** [comment]
Yes, it seems to be the 64-bit version of Python. I am running Python 3.6.0 x64 on a Windows 10 computer, I am attempting to use pyperclip to copy a very long string of obfuscated, encrypted code. inspired by Hacking Secret Ciphers with Python. Pyperclip is giving me the error: 
    File "D:\Documents\Python\obfuscator.py", line 31, in main
    pyperclip.copy(finalcodedata)
    File "D:\Documents\Python\pyperclip.py", line 73, in winSetClipboard
    ctypes.cdll.msvcrt.strcpy(ctypes.c_char_p(pchData), bytes(text, 'ascii'))
    OSError: exception: access violation writing 0x0000000000000000
