### ISSUE TITLE
Add "clip.exe" for Windows copying/pasting

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyperclip#27]
Come up with some way to use Window's clip.exe to copy/paste, in order to fallback if there are issues using the ctypes stuff.

Possible issues:
* clip.exe only copies, it doesn't paste.
* echo Hello | clip.exe will automatically add a newline to the end.

Some info here: http://blogs.msdn.com/b/oldnewthing/archive/2009/11/10/9919908.aspx

**Comment by obskyr** [comment]
Solution for the second issue:
```
import subprocess
clip = subprocess.Popen(['clip'], stdin=subprocess.PIPE)
clip.communicate(input="Hey there.")
```
No newline at the end, and all is good.
