### ISSUE TITLE
Unbelievable hack idea for Windows copy/paste fallback.

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyperclip#35]
A lot of people are reporting problems with copy()/paste() on Windows 10. Pyperclip directly uses ctypes and the win32 api to do the copying and pasting. As an alternative fallback, if that fails, pyperclip could use clip.exe to copy the text. Clip.exe comes with Windows since Vista (XP doesn't have it, but the win32 approach seems to always work for XP).

There is no paste program unfortunately. HOWEVER, here's where my ridiculous plan comes in: There is an open source paste.exe here: http://www.c3scripts.com/tutorials/msdos/paste.html

Pyperclip could store this 4k executable binary as base64 inside its source code. When paste() is called, it can write this out, run it, then delete it. Performance would be terrible, but only if you were running paste constantly in a loop (which is not pyperclip's main case). File-writing and execution permissions would be another issue. Filename collisions would be another. There is, of course, a security issue (similar to tempnames) where an attacker could put in their own file that the Python script would end up running. (This issue currently exists with pyperclip on OS X, which calls pbcopy/pbpaste.)

Any other ideas why this shouldn't be added? Remember, this is a fallback in case the normal approach fails.

**Comment by mhils** [comment]
Can you detail the issues with Windows 10? The Windows tests run fine for me in 90% of the cases, other than that I'm getting what looks like race conditions between copy and paste.
I'll look into the Windows code today - from a first glance it looks like we currently rely on unspecified behaviour, it may be enough to just properly interface the damn Windows API.

> If an application calls OpenClipboard with hwnd set to NULL, EmptyClipboard sets the clipboard owner to NULL; this causes SetClipboardData to fail.

(https://msdn.microsoft.com/de-de/library/windows/desktop/ms649048(v=vs.85).aspx)

**Comment by asweigart** [comment]
That patch solves this issue to the point that I don't think this hack is needed anymore. Thanks!
