### ISSUE TITLE
Import ctypes.wintypes on Linux

### ISSUE THREAD

**Issue by drakulavich** [asweigart/pyperclip#45]
Currently pyperclip imports all clipboards in the head of module:
```
from .clipboards import (init_gtk_clipboard, init_klipper_clipboard, init_osx_clipboard,
                         init_qt_clipboard, init_xclip_clipboard, init_xsel_clipboard, init_no_clipboard)
from .windows import init_windows_clipboard
```
I think it's not necessary, because clipboard types are platform specific. So on Linux you will get [an error from wintypes](https://bugs.python.org/issue16396). It's better to import only platfrom specific functions.

```
>>> import pyperclip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyperclip/__init__.py", line 30, in <module>
    from .windows import init_windows_clipboard
  File "pyperclip/windows.py", line 8, in <module>
    from ctypes.wintypes import HGLOBAL, LPVOID, DWORD, LPCSTR, INT, HWND, HINSTANCE, HMENU, BOOL, UINT, HANDLE
  File "/usr/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
```

What are your opinions, guys?

**Comment by contrixed** [comment]
Check if the platform is Windows and import only the CTypes, for Unix same thing applies. Too keep it sane.

**Comment by mhils** [comment]
I feel that we should rather move the import into init_windows_clipboard, which would be similar to what we do for PyQt and gtk. At the very least, `IS_WINDOWS` should be equivalent to what we do here: https://github.com/asweigart/pyperclip/blob/0d62ebc11fee505ca500ac36c9e341171626989e/pyperclip/__init__.py#L56. On that note, I have no idea why this checks for both `os.name` and `platform.system()`, I just copied it over assuming there was a reason?

FWIW, raising a ValueError when importing the module is actually a bug in Python: http://bugs.python.org/issue16396.

**Comment by contrixed** [comment]
@mhils The reason the check on is Windows differs from that is simple, we also need to check for CYGWIN.

**Comment by mhils** [comment]
@contrixed: _If_ one wants to mirror the existing checks, it should be 
```python
IS_WINDOWS = os.name == 'nt' or platform.system() == 'Windows or 'cygwin' in platform.system().lower()
```
, no?

(If there is no reason for the os.name/platform.system() redudancy, it shoud be simplified at both places)

**Comment by drakulavich** [comment]
Thanks, guys! My solutions is in #50
