### ISSUE TITLE
Pyperclip does not work on Windows XP 32-bit

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyperclip#51]
Pyperclip doesn't work on WIndows XP 32-bit (and possibly 64-bit too). When installing, the following output is received:

    C:\Python34\Scripts>pip install pyperclip
    Collecting pyperclip
      Using cached pyperclip-1.5.24.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\setup.p
    y", line 8, in <module>
            version=__import__('pyperclip').__version__,
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\__init__.py", line 103, in <module>
            copy, paste = determine_clipboard()
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\__init__.py", line 53, in determine_clipboard
            return init_windows_clipboard()
          File "C:\DOCUME~1\admin\LOCALS~1\Temp\pip-build-ncweabkc\pyperclip\pypercl
    ip\windows.py", line 75, in init_windows_clipboard
            wcscpy_s = ctypes.cdll.msvcrt.wcscpy_s
          File "C:\Python34\lib\ctypes\__init__.py", line 364, in __getattr__
            func = self.__getitem__(name)
          File "C:\Python34\lib\ctypes\__init__.py", line 369, in __getitem__
            func = self._FuncPtr((name_or_ordinal, self))
        AttributeError: function 'wcscpy_s' not found

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\DOCUME~1\admin
    \LOCALS~1\Temp\pip-build-ncweabkc\pyperclip

When I try to modify the code to use `ctypes.cdll.msvcrt.wcscpy` instead of `ctypes.cdll.msvcrt.wcscpy_s`, this quick fix just results in this error:

    >>> import pyperclip
    >>> pyperclip.copy('howdy')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python34\pyperclip\windows.py", line 142, in copy_windows
        if wcscpy_s(c_wchar_p(locked_handle), count, c_wchar_p(text)):
    OSError: exception: access violation reading 0x00000006

This is probably an issue that wcscpy_s doesn't exist in the old msvcrt.dll. I was able to replicate this in a VM. I'm not sure if this can be fixed by updating the dll, but we should come up with a better solution than that.

**Comment by seasalt** [comment]
Thanks . It should help. I noticed last night when was asked to restart my
comp

**Comment by mhils** [comment]
Just my 5 cents: Windows XP is EOL, so IMHO there's really no reason to fix that.

**Comment by drakulavich** [comment]
I'm not sure, but may be runtime libraries will help?
https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by mhils** [comment]
Nonwithstanding my opinion on Windows XP support: IMO the best way to fix that is using `memcpy`, which we ultimately need to use anyway if we want to support other formats than text.

**Comment by hynekcer** [comment]
The easiest and recommended  way to copy memory is [`ctypes.memmove`](https://docs.python.org/3.5/library/ctypes.html#ctypes.memmove). It is independent on the platform and libraries.
