### ISSUE TITLE
test_copy_paste_unicode fails with 'ascii' codec can't encode character u'\u0ca0'

### ISSUE THREAD

**Issue by sdelafond** [asweigart/pyperclip#53]
Here is the complete error:

````
======================================================================
ERROR: test_copy_paste_unicode (__main__.TestQt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_copy_paste.py", line 64, in test_copy_paste_unicode
    self.assertEqual(self.paste(), msg)
  File "tests/../pyperclip/clipboards.py", line 52, in paste_qt
    return str(cb.text())
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0ca0' in position 0: ordinal not in range(128)

----------------------------------------------------------------------
Ran 56 tests in 0.063s

FAILED (errors=1, skipped=42)
````

This is with 1.5.24, on linux. My current locale is a UTF-8 one, so I'm not sure what's wrong.

**Comment by mhils** [comment]
Which Python version is that?

**Comment by sdelafond** [comment]
This is 2.7.10.

**Comment by mhils** [comment]
Thanks. I think https://github.com/asweigart/pyperclip/commit/d2abbc02a91ab26d8bbfdcbf8798f994b885052e#diff-9c05b906b6e6d3b814fd59df89841e48L53 removes a perfectly valid comment here. :-) I can't test this at the moment, but just using `STRING_FUNCTION` should do it. Bonus points for renaming that to `text_type`, which matches what `six` calls it.

**Comment by drakulavich** [comment]
It's strange. I've ran test_copy_paste.py with `str(cb.text())`. Didn't find any issues for Qt functions.
Python 2.7.10, UTF-8 locale, Ubuntu.

@sdelafond, did `unicode(cb.text())` help you?

**Comment by sdelafond** [comment]
s/str/unicode/ in paste_qt() does fix the issue on my end.

**Comment by drakulavich** [comment]
Thank you for reply. I'll prepare a patch in a couple of hours.
