### ISSUE TITLE
Use TKinter if possible

### ISSUE THREAD

**Issue by budziq** [asweigart/pyperclip#57]
Most python deployments have TKinter. This should be way more portable than usage of gtk / qt / xclip and xsel as well a much faster than popen

```python
try:
    from Tkinter import Tk
except ImportError:
    from tkinter import Tk

def clip_set(text):
     r=Tk()
     r.withdraw()
     r.clipboard_clear()
     r.clipboard_append(text)
     r.destroy()


def clip_get():
     r=Tk()
     r.withdraw()
     ttt = r.clipboard_get()
     r.destroy()
     return ttt
```

**Comment by drakulavich** [comment]
I have tested your code in arch linux with tk 8.6.4. It didn't change system clipboard.
Maybe [these methods](http://wiki.tcl.tk/1423) work only with Tk clipboard.

**Comment by budziq** [comment]
Right you are. I have forgotten to test it outside of interpreter ...
