### ISSUE TITLE
Ubuntu Package lists PyQt4 and xclip as dependencies.

### ISSUE THREAD

**Issue by mhils** [asweigart/pyperclip#68]
Not directly a pyperclip issue, but the pyperclip Ubuntu package declares PyQt4 and xclip as a dependency. As a consequence, all packages that depend on pyperclip transitively depend on libqt4, libx11, etc.. We had a few mitmproxy users who were not so amused by this (especially if you install it on Ubuntu Server...), and I'd love to start a discussion how this could be tackled. As I see it, pyperclip should list none of those as a dependency.

http://packages.ubuntu.com/de/xenial/python-pyperclip

cc @sdelafond

**Comment by sdelafond** [comment]
I agree, this is less than optimal, but not a pyperclip issue. My package should instead most likely depend on xclip OR xsel OR python-qt4. I'll make that change soon, but this github issue can safely be closed.

**Comment by asweigart** [comment]
I'm closing this issue. Please re-open it if this needs attention again.
