### ISSUE TITLE
pyperclip.copy() returns None

### ISSUE THREAD

**Issue by Almoullim** [asweigart/pyperclip#69]
```
import pyperclip
print(repr(pyperclip.copy('Text')))
```

Returns

```
[Almoullim] /home/ali/Dev/python3 % python3 ext.py
None
```

if i use pyperclip from the terminal it works, but when i use it inside a .py file it doesn't

**Comment by jaraco** [comment]
That's right. By design the 'copy' function doesn't return anything (which on Python means it returns None). What else would you expect it to return?

**Comment by hugovk** [comment]
This can be closed.
