### ISSUE TITLE
pyperclip module not working at all???

### ISSUE THREAD

**Issue by jam051** [asweigart/pyperclip#71]
I am learning Python by first reading Automate the Boring Stuff With Python and have just got to Chapter 6 and am trying to get the pyperclip module to work.  I have followed the instructions and installed / uninstalled on two different systems ( Win 7 x64 and Win 10 x64, Python v3.5.1 ) and can get the following lines to run if typed directly into the interactive shell :

import pyperclip
pyperclip.copy('Hello world!')
pyperclip.paste()

But when using IDLE and trying to run using F5 + Save, it gives the error below :

================================ RESTART: C:\Python\pyperclip.py ================================
Traceback (most recent call last):
  File "C:\Python\pyperclip.py", line 1, in <module>
    import pyperclip
  File "C:\Python\pyperclip.py", line 2, in <module>
    pyperclip.copy('Hello world!')
AttributeError: module 'pyperclip' has no attribute 'copy'

Any help would be greatly appreciated.

Thanks!!!

**Comment by jaraco** [comment]
You should avoid naming your file with the same name as the module. Most likely you're failing to import the `pyperclip` package, but instead just importing the script you're running, which obviously has no `copy` attribute. Just rename your file to pyperclip_test.py and your issue will go away.

**Comment by hugovk** [comment]
@jam051 Did the above solve your problem?

I think issue can be closed.

**Comment by jam051** [comment]
Please close.  Thank you.
