### ISSUE TITLE
Pyperclip not working in Win10 Python 3.5.3

### ISSUE THREAD

**Issue by heliophagus** [asweigart/pyperclip#92]
Big fan of your book, by the way! But regarding Pyperclip -

Pyperclip installs fine. Copies OK to the Win clipboard. BUT --

When I try to paste anything FROM the clipboard, whether copied from within Pyperclip or from within Win, as in:

pyperclip.paste()

I get this:

'<function init_windows_clipboard.<locals>.paste_windows at 0x000002CD1B289400>'

This is not quite what I need. Do you have any suggestions? I really do need to get this working.

**Comment by martingv** [comment]
Are you sure you're including the brackets in `pyperclip.paste()`?

I get a similar output if I omit the brackets `pyperclip.paste`, but it works fine with brackets.

**Comment by jim-hart** [comment]
@heliophagus, check out @ghost response.  That's not an error message, it's the correct response from Python if parenthesis aren't included at the end of the function.  When used without parenthesis, the response you get is the representation of `pyperclip.paste` as an object. 

Regardless, I made a Python 3.5.3 conda environment to test this just to verify, and `pyperclip.paste()` works as intended.
![pyperclip_test](https://user-images.githubusercontent.com/24954159/30260146-a1110b66-9693-11e7-8954-ba1c5c182239.png)

**Comment by sudo-WearTherinG** [comment]
# simple workaround
# i am having problem with pyperclip.paste() too
 
import pyautogui
import pyperclip
  
# 'x' 'y' coordinates of mouse
pyautogui.click(x=1755, y=673, duration = 1)

# copying text to clipboard 
pyperclip.copy('github.com')

# now paste it
pyautogui.hotkey('ctrl', 'v')

**Comment by lanouvelle** [comment]
i am having problem with pyperclip.paste() too
