### ISSUE TITLE
[Solved]Can't import into Python 3.6

### ISSUE THREAD

**Issue by catinsunshine** [asweigart/pyperclip#95]
Hi Sir,

pyperclip 1.5.27 runs well on Python 3.5 on Debian, but failed to import into 3.6 as following. 
```
>>> import pyperclip
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'
```
I have reinstalled it with pip3 but still failed. Will u upgrade to support it? MTKS

**Comment by catinsunshine** [comment]
Pls ignore it. Just find the solution.

The default Python 3 version in Debian is 3.5. Seems pip3 will install into 3.5. So, when I installed 3.6, need install pyperclip with below command:

```
peter@Debian:~$ python3.6 -m pip install pyperclip
Successfully installed pyperclip-1.5.27
```
Docs refer:
[https://docs.python.org/3/installing/index.html?highlight=pip#work-with-multiple-versions-of-python-installed-in-parallel](https://docs.python.org/3/installing/index.html?highlight=pip#work-with-multiple-versions-of-python-installed-in-parallel)

**Comment by SriVinayA** [comment]
still it's not working for me.
